Add and raise library exceptions
home-assistant-libs/pydroid-ipcam pull request #117
Opened 2022-08-08 13:23 UTC by engrbm87

2022-08-08 16:50 UTC, MartinHjelmare requested changes

2022-08-08 16:50 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
> +            _LOGGER.error("Incorrect username or password")
We shouldn't log and raise an exception. Include the message as an exception argument instead.

2022-08-08 16:50 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
> +            _LOGGER.error("Incorrect username or password")
Do we know that all client response errors are failed authentication? We don't need to check status code eg 401 or 403?

2022-08-08 16:50 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
>                  if response.status == 200:
Do we still need this check when using `raise_for_status`?

2022-08-09 07:47 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
> +                raise Unauthorized("Username or password are incorrect") from error
```suggestion
                raise Unauthorized("Incorrect username or password") from error
```

2022-08-09 07:48 UTC, MartinHjelmare commented
Please describe the main changes in the PR description as this will be a breaking change.

2022-08-09 08:15 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
>      async def _request(self, path: str) -> Union[bool, Dict[str, Any], None]:
Can we ever return `None` now or should we update `data` type and return typing here.

2022-08-09 08:27 UTC, engrbm87 commented on pydroid_ipcam/__init__.py
>      async def _request(self, path: str) -> Union[bool, Dict[str, Any], None]:
Can we remove `data` and do this instead `return await response.json()`?

2022-08-09 08:36 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
>      async def _request(self, path: str) -> Union[bool, Dict[str, Any], None]:
We need to add some type information on the return value of `response.json` somewhere as it would otherwise be typed as `Any`.

We also need to still return a boolean for the text response parsing.

Make a suggestion, if you have an idea. :+1:

2022-08-09 09:39 UTC, MartinHjelmare commented on pydroid_ipcam/__init__.py
>      async def _request(self, path: str) -> Union[bool, Dict[str, Any], None]:
Long term we should probably refactor and return the `ClientResponse` from `_request` and do the response parsing in each client endpoint method instead. It's those methods that know how to do the parsing and what return value is expected.

2022-08-09 09:40 UTC, MartinHjelmare approved these changes
Great!

2022-08-09 09:40 UTC, merged

2022-08-09 09:41 UTC, MartinHjelmare commented
Should I make a release including this PR now?

2022-08-09 09:54 UTC, engrbm87 commented
> 

I think we should first refactor the return of the value and unit. Then we can make a release. What do you think?

2022-08-09 10:02 UTC, MartinHjelmare commented
Sounds good! :+1:

2022-08-15 12:53 UTC, MartinHjelmare commented
2.0.0 release:
https://github.com/home-assistant-libs/pydroid-ipcam/releases/tag/2.0.0